distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip
wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.3.2/maven-wrapper-3.3.2.jar
distributionSha512Sum=900f28e6b2fb1f868d47f39acdedc9baa176dc8728748cf3213807de8cae8ef2dd71ef9b2f316b2bbf733b2b78c36decbfd660e21746b8e253f5764b603d3842
